// App config
export const APP_DOMAIN = 'APP_DOMAIN';
export const APP_API_PREFIX = 'APP_API_PREFIX';

// Auth config
export const AUTH_JWT_EXPIRES_IN = 'AUTH_JWT_EXPIRES_IN';
export const AUTH_JWT_ALGORITHM = 'AUTH_JWT_ALGORITHM';
export const AUTH_JWT_PRIVATE_KEY = 'AUTH_JWT_PRIVATE_KEY';
export const AUTH_JWT_PUBLIC_KEY = 'AUTH_JWT_PUBLIC_KEY';
export const AUTH_GOOGLE_CLIENT_ID = 'AUTH_GOOGLE_CLIENT_ID';
export const AUTH_GOOGLE_CLIENT_SECRET = 'AUTH_GOOGLE_CLIENT_SECRET';
export const AUTH_GOOGLE_CALLBACK_URL = 'AUTH_GOOGLE_CALLBACK_URL';
export const AUTH_SESSION_COOKIE_KEY = 'zenith_session';

// Mailer config
export const MAILER_TRANSPORT_HOST = 'MAILER_TRANSPORT_HOST';
export const MAILER_TRANSPORT_TLS = 'MAILER_TRANSPORT_TLS';
export const MAILER_AUTH_USER = 'MAILER_AUTH_USER';
export const MAILER_AUTH_PASS = 'MAILER_AUTH_PASS';
export const MAILER_DEFAULTS_FROM = 'MAILER_DEFAULTS_FROM';

// Google CLoud Storage
export const STORAGE_BUCKET = 'STORAGE_BUCKET';
export const STORAGE_PROJECT_ID = 'STORAGE_PROJECT_ID';
export const STORAGE_CLIENT_EMAIL = 'STORAGE_CLIENT_EMAIL';
export const STORAGE_MAX_RETRIES = 'STORAGE_MAX_RETRIES';
export const STORAGE_AUTO_RETRY = 'STORAGE_AUTO_RETRY';

//Date Time format
export const DATE_TIME_FORMAT = 'YYYY-MM-DD';
